allowBuilds:
  '@astryxdesign/cli': true
  '@astryxdesign/core': true
  '@swc/core': true
  bufferutil: false
  esbuild: true
  sharp: true
  unrs-resolver: false
  utf-8-validate: false
minimumReleaseAgeExclude:
  - '@next/env@16.4.0-canary.25'
  - '@next/swc-darwin-arm64@16.4.0-canary.25'
  - '@next/swc-darwin-x64@16.4.0-canary.25'
  - '@next/swc-linux-arm64-gnu@16.4.0-canary.25'
  - '@next/swc-linux-arm64-musl@16.4.0-canary.25'
  - '@next/swc-linux-x64-gnu@16.4.0-canary.25'
  - '@next/swc-linux-x64-musl@16.4.0-canary.25'
  - '@next/swc-win32-arm64-msvc@16.4.0-canary.25'
  - '@next/swc-win32-x64-msvc@16.4.0-canary.25'
  - next@16.4.0-canary.25
  - react-dom@19.3.0
  - react@19.3.0
  - scheduler@0.28.0
  - '@next/playwright@16.4.0-canary.25'
  - '@types/node@26.5.1'
  - '@types/react-dom@19.3.0'
  - '@types/react@19.3.0'
  - '@next/eslint-plugin-next@16.4.0-canary.25'
  - eslint-config-next@16.4.0-canary.25
